import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '../styles/Home.module.css'

import { Transaction, SystemProgram } from '@solana/web3.js'

const FEWA = () => {
  const tx = new Transaction()
  tx.add({
    keys: [],
    programId: SystemProgram.programId,
    data: Buffer.from(''),
  });
  tx.recentBlockhash = '11111111111111111111111111111111'
  tx.feePayer = SystemProgram.programId

  return <>
    {tx.serialize().length}
  </>;
}

const AWEF = dynamic(() => Promise.resolve(FEWA), { ssr: false })

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AWEF />
    </div>
  )
}

export default Home
